---
# basic information
title: "Paper Manuscript"
keywords: [keyword1, keyword2]
thanks: Thanks to everyone for checking this out.

# information used by aog-article format
shorttitle: "Paper"
shortauthors: Gullickson

## bibliographic information is in the _quarto.yml for the project ##

# I use the abstact-section extension to write abstracts as a normal section
# of the document. If you prefer to write abstracts in yaml, you can comment
# out the filter and uncomment the abstract line.
#abstract: An Abstract
filters:
  - abstract-section

# default formats
# I use a custom aog-article-pdf available as an extension, but this can be 
# replaced with the default pdf format. The submittable extenstion
# also gives me submittable-pdf and submittable-docx for journal submission
# entries, but I leave those commented out until I need them.
format:
  aog-article-pdf:
    keep-tex: false
  #pdf: 
  #  keep-tex: false
  #submittable-pdf:
  #  keep-tex: false
  #  titlepage: true
  #  endnotes: false
  #  fig-pos: "!t"
  #submittable-docx: default
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

# Abstract

Abstract goes here.

# Introduction

This quarto doc is for writing the manuscript. This is a test citation [@alba1990].

# Background

# Data and Methods
Independent Variable (IV): State Renewable Portfolio Standards (RPS)
The independent variable is derived from the dataset U.S. State Electricity Resource Standards: 2024 Status Update, compiled by the Lawrence Berkeley National Laboratory (LBNL). The dataset provides information on state-level Renewable Portfolio Standards (RPS) and Clean Energy Standards (CES) across U.S. states, including policy adoption dates, renewable energy targets, and compliance timelines. For this study, the dataset can be used to measure whether a state has adopted an RPS policy and the strength of the policy target over time, though the research only focus on 2008 and 2009. 


Dependent Variable (DV): Renewable Electricity Generation Share
The dependent variable is drawn from the U.S. Energy Information Administration (EIA) Annual Energy Review renewable electricity generation dataset. The dataset provides state-level information on electricity generation and the percentage of generation derived from renewable energy sources in 2008 and 2009. In this study, the dependent variable is the share of electricity generation from renewable energy sources, with particular attention to the “percent non-hydro renewable” measure, which captures renewable generation from sources such as wind, solar, geothermal, and biomass while excluding conventional hydroelectric power. This measure is appropriate because it reflects the types of renewable energy sources most directly influenced by modern RPS policies.


# Results

# Conclusions


<!-- Explicitly place references -->
# References
Data source: Lawrence Berkeley National Laboratory RPS Dataset
Data source: U.S. Energy Information Administration Renewable Energy Annual Data

::: {#refs}
:::

